Repository zeit-ui/zeit-style, pull requests merged in 2019-02, with the labels that each got.

#2 fix(summary): fix github link
  README.md
  src/templates/summary.pug
Labels: want merge

#3 feat: add components
  package.json
  src/styles/basics/card.styl
  src/styles/basics/paragraphs.styl
  src/styles/components/footnote.styl
  src/styles/components/index.styl
  src/styles/components/input.styl
  src/styles/components/switcher.styl
  src/styles/components/tag.styl
  src/styles/fonts/iconfont.css
  src/styles/fonts/iconfont.eot
  src/styles/fonts/iconfont.svg
  src/styles/fonts/iconfont.ttf
  src/styles/fonts/iconfont.woff
  src/styles/fonts/iconfont.woff2
  src/styles/vars/colors.styl
  src/templates/basics/card.pug
  src/templates/basics/heading.pug
  src/templates/components/badge.pug
  src/templates/components/button.pug
  src/templates/components/checkbox.pug
  src/templates/components/code.pug
  src/templates/components/collapse.pug
  src/templates/components/footnote.pug
  src/templates/components/index.pug
  src/templates/components/switcher.pug
  src/templates/components/tag.pug
  src/templates/index.pug
  src/templates/side.pug
  src/templates/styles/layout.styl
  src/templates/styles/side.styl
Labels: docs, feature

#4 release: v0.2.1
  README.md
  package.json
  src/styles/fonts/iconfont.css
Labels: docs, feature

#5 fix: fix style in mobile and webkit
  package.json
  src/styles/components/button.styl
  src/styles/components/checkbox.styl
  src/styles/components/input.styl
  src/styles/components/switcher.styl
  src/templates/styles/layout.styl
Labels: bug, test passed, want merge

#6 fix: fix component style
  package-lock.json
  package.json
  src/styles/components/avatar.styl
  src/styles/components/badge.styl
  src/styles/components/button.styl
  src/styles/components/input.styl
  src/styles/components/note.styl
  src/styles/vars/index.styl
  src/styles/vars/status.styl
  src/templates/components/avatar.pug
  src/templates/components/badge.pug
Labels: bug, testing, work in progress

#7 build(pkg): release v0.2.4
  package-lock.json
  package.json
  src/styles/components/avatar.styl
  src/templates/summary.pug
Labels: want merge

#8 chore(pkg): release v0.2.6
  package-lock.json
  package.json
  src/styles/components/button.styl
  src/templates/components/button.pug
Labels: bug, want merge

#9 fix: fix checked style
  package-lock.json
  package.json
  src/styles/components/checkbox.styl
  src/templates/components/checkbox.pug
Labels: bug, test passed, want merge

#10 chore(pkg): release alpha.12
  package-lock.json
  package.json
  src/styles/components/fieldset.styl
  src/styles/components/input.styl
  src/styles/fonts/iconfont.css
  src/styles/fonts/iconfont.eot
  src/styles/fonts/iconfont.svg
  src/styles/fonts/iconfont.ttf
  src/styles/fonts/iconfont.woff
  src/styles/fonts/iconfont.woff2
  src/templates/components/input.pug
Labels: bug, want merge

#11 feat: fix select and button style
  package-lock.json
  package.json
  src/styles/components/button.styl
  src/styles/components/select.styl
  src/templates/components/select.pug
Labels: bug, need review, want merge

#12 chore(pkg): release 0.3.0
  README.md
  now.json
  package-lock.json
  package.json
  src/styles/basics/paragraphs.styl
  src/styles/components/index.styl
  src/styles/components/rate.styl
  src/styles/components/tag.styl
  src/styles/fonts/iconfont.css
  src/styles/fonts/iconfont.eot
  src/styles/fonts/iconfont.svg
  src/styles/fonts/iconfont.ttf
  src/styles/fonts/iconfont.woff
  src/styles/fonts/iconfont.woff2
  src/styles/vars/colors.styl
  src/templates/basics/paragraph.pug
  src/templates/components/index.pug
  src/templates/components/rate.pug
  src/templates/components/tag.pug
  src/templates/side.pug
Labels: feature, want merge

#13 feat: init toast and improve button
  package-lock.json
  package.json
  src/styles/components/button.styl
  src/styles/components/index.styl
  src/styles/components/rate.styl
  src/styles/components/toast.styl
  src/templates/components/button.pug
  src/templates/components/index.pug
  src/templates/components/toast.pug
Labels: feature, test passed, want merge

#14 feat(spinner): init component
  package-lock.json
  package.json
  src/styles/components/index.styl
  src/styles/components/spinner.styl
  src/templates/components/index.pug
  src/templates/components/spinner.pug
Labels: feature, want merge

#15 feat: optimize style in mobile screen
  package-lock.json
  package.json
  src/styles/basics/layout.styl
  src/templates/styles/layout.styl
  src/templates/styles/side.styl
  src/templates/summary.pug
  yarn.lock
Labels: feature, want merge

#18 feat(popover): init component and examples
  .circleci/config.yml
  .travis.yml
  package.json
  src/styles/components/index.styl
  src/styles/components/popover.styl
  src/styles/components/transition.styl
  src/templates/components/index.pug
  src/templates/components/popover.pug
  src/templates/side.pug
Labels: feature, need review, want merge

#16 feat(radio): add radio component
  .gitignore
  src/styles/components/index.styl
  src/styles/components/radio.styl
  src/templates/components/index.pug
  src/templates/components/radio.pug
  src/templates/side.pug
Labels: feature

#19 chore: release v0.5.0
  package.json
Labels: want merge

#20 fix(switcher): fix hover
  src/styles/components/switcher.styl
Labels: bug, need review, want merge

#21 chore: release v0.6.1
  package.json
  src/styles/basics/card.styl
  src/templates/basics/card.pug
Labels: want merge

#22 fix(switcher): fix active style
  src/styles/components/switcher.styl
Labels: bug, need review, want merge
