Repository zeit-ui/zeit-style, pull requests merged in 2019-03, with the labels that each got.

#23 fix: fix shadow style when type enabled
  package.json
  src/styles/components/button.styl
  src/templates/components/button.pug
Labels: bug, want merge

#25 fix: add progress component and styl
  src/styles/components/index.styl
  src/styles/components/progress.styl
  src/templates/components/index.pug
  src/templates/components/progress.pug
  src/templates/side.pug
Labels: feature, need review, want merge

#26 chore: release v0.7.0
  package.json
Labels: want merge

#27 fix: progress style bug
  package.json
  src/styles/components/progress.styl
  src/templates/components/progress.pug
Labels: bug, need review

#28 fix(progress): add fix style
  package.json
  src/styles/components/progress.styl
Labels: need review, want merge
